# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c09383506f3906292e236b91a211e8147e33084ce7ef6756b602218e6fe12e658da772a774ea0605d33ec37d035868a8ab97672c0a01525eaa59fb462aa0570f

test:
  secret_key_base: 6892e9be54c6460769280fdcc7d11b7ba8363535e12eb6badb14697fe562fa3096e0c2382856d66c6ffac0ca8a524a2f138dd4541d6a47f41c9d6664651adf9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
